project:
  type: website

website:
  title: "Welcome to my blog!!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dyoung757
      - icon: linkedin
        href: https://https://www.linkedin.com/in/donnovan-young-ii/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

